---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: alias={{ .Values.image.repository }}:{{ .Values.image.tag }}
    argocd-image-updater.argoproj.io/alias.update-strategy: digest
    argocd-image-updater.argoproj.io/alias.force-update: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: {{ .Values.appName }}
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  project: sampleapp
  source:
    repoURL: {{ .Values.repoURL | replace ".git" " " | quote }}
    targetRevision: {{ .Values.chart.version }}
    chart: {{ .Values.chart.name }}
    helm:
      releaseName: test
      values: |
        image:
          repository: {{ .Values.image.repository }}
        ingress:
          env: {{ .Values.clusterSubdomain }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=false
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
