---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: alias={{ .Values.image.repository }}
    argocd-image-updater.argoproj.io/alias.update-strategy: latest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: {{ printf "%s-%s" .Values.appNamePrefix (default "" .Values.appName)| trunc 63 | trimSuffix "-" }}
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.tenantName }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.path }}
    helm:
      releaseName: test
      values: |
        image:
          repository: {{ .Values.image.repository }}
          pullPolicy: {{ .Values.image.pullPolicy }}
          tag: {{ .Values.image.tag }}
        ingress:
          host: {{ .Values.ingress.host }}
          env: {{ .Values.clusterSubdomain }}
        region: {{ .Values.region }}
        securityContext: {{ .Values.securityContext }}
        replicaCount: {{ .Values.replicaCount }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=false
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
