---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: alias=ghcr.io/dnv-gssit/kubeit-example:latest
    argocd-image-updater.argoproj.io/alias.update-strategy: digest
    argocd-image-updater.argoproj.io/alias.force-update: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: simple-example
spec:
  destination:
    namespace: simple-example
    server: https://kubernetes.default.svc
  project: sampleapp
  source:
    repoURL: https://github.com/dnv-gssit/kubeit-example.git
    chart: example
    helm:
      releaseName: test
      values: |
        image:
          repository: ghcr.io/dnv-gssit/kubeit-example
        ingress:
          env: nonprod002
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
      limit: 2
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=false
