namespace: tenant2-helm

appNamePrefix: example
path: "helm/example"

image:
  repository: ghcr.io/dnv-gssit/kubeit-example
  tag: latest
  pullPolicy: Always

ingress:
  host: nginx-demo

replicaCount: 1
