kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "example.fullname" . }}
  labels:
    {{- include "example.labels" . | nindent 4 }}
data:
  html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to DNV nginx!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Welcome to DVN nginx!</h1>
    <p>If you see this page for enviroment {{ .Values.ingress.env }}, region {{ .Values.region }},
    namespace {{ .Release.Namespace }}
    the nginx web server is successfully installed and
    working.</p>

    <p><em>Thank you.</em></p>
    </body>
    </html>
